name: mix_flutter_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: 'v1.12.13-hotfixes'


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.tradwang.mix_flutter_flutter
    iosBundleIdentifier: com.tradwang.mixFlutterFlutter
