platform:ios,'9'

flutter_application_path = '../mix_flutter_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'mix_flutter_ios' do
    install_all_flutter_pods(flutter_application_path)
end